### ISSUE TITLE
Tabelas

### ISSUE THREAD

**Issue by cwsilva1** [victor1162/sistema-parana#1]
Olá amigo dev,

estava dando uma olhada em seu sistema e fiquei impressinonado, parabéns pelo trabalho.

entretanto em meus testes verifiquei que está faltando cadastrar algumas tabelas aonde você não informou no readme.md , gostaria de continuar testando para afins de estudo. consegue me passar o restante das tabelas para continuar ?

desde já agradeço

**Comment by victor1162** [comment]
Olá meu amigo Carlos, passo sim vou da uma atualizada lá amanhã, falta colocar algumas tabelas do banco de dados mesmo.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
From: Carlos Weiber ***@***.***>
Sent: Saturday, October 16, 2021 8:22:20 PM
To: victor1162/sistema-parana ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [victor1162/sistema-parana] Tabelas (#1)


Olá amigo dev,

estava dando uma olhada em seu sistema e fiquei impressinonado, parabéns pelo trabalho.

entretanto em meus testes verifiquei que está faltando cadastrar algumas tabelas aonde você não informou no readme.md , gostaria de continuar testando para afins de estudo. consegue me passar o restante das tabelas para continuar ?

desde já agradeço

**Comment by cwsilva1** [comment]
Olá Victor,

Validei as tabelas e fiz os ajustes aqui.

Tabela faltando "tb_veiculos" com as colunas (cera, resina, placa, modelo, cor_veiculo, valor, data_lavagem, hora_lavagem, lavagem_comum) ;
Fora a coluna "valor" que é uma int, todos os outros serão varchar 
Ajuste no null na coluna "enviar_email" que esta na tabela "tb_empresas" ;

seguindo com os testes agora e está tudo ok.
mais uma vez parabéns !

**Comment by victor1162** [comment]
Isso perfeito, é porque eu subi a outra versão pro git, e acabei esquecendo de atualizar as tabelas do banco de dados, mais que bom que vc conseguiu depois vou colocar o restante do código atualizado

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
